apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: devops-portfolio-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
configMapGenerator:
  - name: devops-portfolio-api-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
